initial CD

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -36,3 +36,50 @@ jobs:
           dotnet-version: 6.0.x
       - name: Build
         run: dotnet build --configuration=Release
+  
+  package:
+    runs-on: windows-2019
+    needs: HiddenWindow
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Setup .NET SDK v6.0.x
+        uses: actions/setup-dotnet@v3
+        with:
+          dotnet-version: 6.0.x
+      - name: Create NuGet packages
+        run: |
+          if (-not ("${{ github.ref }}" -like "refs/tags/v*")) {
+            $suffix = "preview-$(Get-Date -Format yyyyMMddHHmmss -AsUTC)-$(git rev-parse --short HEAD)"
+            $params = "--version-suffix", $suffix
+          }
+          dotnet pack --configuration=Release --output dist @params
+          if ("${{ github.ref }}" -like "refs/tags/v*") {
+              $tag = "${{ github.ref }}".SubString(11)
+              $expectedHiddenWindowFile = "dist/HiddenWindow.$tag.nupkg"
+              # Check whether the tag and the package version match together
+              if (-not (Test-Path -Path $expectedHiddenWindowFile)) {
+                  echo "::error ::Expected file $expectedHiddenWindowFile doesn't exist"
+                  exit 1
+              }
+          }
+      - name: Upload NuGet package artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          name: nuget-packages
+          path: dist/*.nupkg
+
+  # Publish NuGet packages when a tag is pushed.
+  # Build needs to succeed first, including having a tag name that matches the version number.
+  publish-release:
+    if: ${{ !github.event.repository.fork && startsWith(github.ref, 'refs/tags/v') }}
+    needs: package
+    runs-on: ubuntu-18.04
+    steps:
+      - name: Download NuGet package artifacts
+        uses: actions/download-artifact@v3
+        with:
+          name: nuget-packages
+          path: dist
+      - name: Publish to NuGet
+        run: dotnet nuget push "dist/HiddenWindow.*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
