add tag match check
the check is done in the publish step, as to succeed, the github action job needs to be originally triggered by a tag or a master build so that NGV
does NOT add the commit info to the package name.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -67,7 +67,7 @@ jobs:
   publish-release:
     if: ${{ !github.event.repository.fork && startsWith(github.ref, 'refs/tags/v') }}
     needs: package
-    runs-on: ubuntu-18.04
+    runs-on: windows-2019
     steps:
       - name: Download NuGet package artifacts
         uses: actions/download-artifact@v3
@@ -75,4 +75,19 @@ jobs:
           name: nuget-packages
           path: artefacts
       - name: Publish to NuGet
-        run: dotnet nuget push "artefacts/HiddenWindow.${{ env.NBGV_NuGetPackageVersion }}.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
+        run: |
+          if (-not ("${{ github.ref }}" -like "refs/tags/v*")) {
+              $suffix = "preview-$(Get-Date -Format yyyyMMddHHmmss -AsUTC)-$(git rev-parse --short HEAD)"
+              $params = "--version-suffix", $suffix
+          }
+          if ("${{ github.ref }}" -like "refs/tags/v*") {
+              $tag = "${{ github.ref }}".SubString(11)
+              $expectedHiddenWindowFile = "artefacts/HiddenWindow.$tag.nupkg"
+
+              # Check whether the tag and the package version match together
+              if (-not (Test-Path -Path $expectedHiddenWindowFile)) {
+                  echo "::error ::Expected file $expectedHiddenWindowFile doesn't exist"
+                  exit 1
+              }
+          }
+          dotnet nuget push "artefacts/HiddenWindow.${{ env.NBGV_NuGetPackageVersion }}.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
