Add continuous delivery and bump version

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -36,3 +36,54 @@ jobs:
           dotnet-version: 6.0.x
       - name: Build
         run: dotnet build --configuration=Release
+  
+  package:
+    runs-on: windows-latest
+    needs: HiddenWindow
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - name: Setup .NET SDK v6.0.x
+        uses: actions/setup-dotnet@v3
+        with:
+          dotnet-version: 6.0.x
+      - name: Build and package
+        run: dotnet build --configuration=Release
+      - name: Nerdbank.GitVersioning
+        uses: dotnet/nbgv@master
+        with:
+          setAllVars: true
+      - run: echo "Package generated artefacts/HiddenWindow.${{ env.NBGV_NuGetPackageVersion }}.nupkg"
+      - name: Upload NuGet package artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          name: nuget-packages
+          path: artefacts/*.nupkg
+
+  # Publish NuGet packages when a tag is pushed.
+  # Build needs to succeed first, including having a tag name that matches the version number.
+  publish-release:
+    if: ${{ !github.event.repository.fork && startsWith(github.ref, 'refs/tags/v') }}
+    needs: package
+    runs-on: windows-latest
+    steps:
+      - name: Download NuGet package artifacts
+        uses: actions/download-artifact@v3
+        with:
+          name: nuget-packages
+          path: artefacts
+      - name: Publish to NuGet
+        run: |
+          if ("${{ github.ref }}" -like "refs/tags/v*") {
+              $tag = "${{ github.ref }}".SubString(11)
+              $expectedHiddenWindowFile = "artefacts/HiddenWindow.$tag.nupkg"
+
+              # Check whether the tag and the package version match together
+              if (-not (Test-Path -Path $expectedHiddenWindowFile)) {
+                  echo "::error ::Expected file $expectedHiddenWindowFile doesn't exist"
+                  exit 1
+              }
+              dotnet nuget push "artefacts/HiddenWindow.${{ env.NBGV_NuGetPackageVersion }}.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
+          }
